### PR TITLE
Make many things async and await Lisp#run

### PR DESCRIPTION
**Pull request by erbridge**
Lisp#run is an async function, so everything that calls it should also be async. I've opted for explicitly making things async even when the JS API that calls it doesn't do anything to specifically handle the promise to help document expectations. This will make it easier to do spot places that need error handling later.

This also means `_run` only has "active" for as long as it's actually running, rather than relying on a timer.

### CODE REVIEW

**Comment by neauoire** [comment]
thanks a lot :)

**Comment by erbridge** [comment]
Heads up @neauoire, this appears to have been dropped from `master`. Fine if intentional.

**Comment by neauoire** [comment]
Yes, sorry. I merged it, it broke the mouse cursor and few other things, but I picked the parts that worked, and reverted.

**Comment by erbridge** [comment]
Ah that's a shame. I might take another look at it. I saw some odd behaviour, that could be accounted for by a race condition, which is what I was looking at solving.

**Pull request merged**
