### PR TITLE
Add theme op to library to get theme variables.

### PR DESCRIPTION
**Pull request by AAorris**
Screen Shot 2019-07-14 at 11 00 15 AM

### CODE REVIEW

**Comment by lctrt** [comment]
I would not put the package-lock into .gitignore, we should add this to the repo at some point. About the actual feature, I quite like it :)

**Comment by AAorris** [comment]
Whoops! That was an untracked file reflex.

**Comment by AAorris** [comment]
Consideration here is that the lisp is pretty agnostic of the javascript hort language so far and the --var syntax would leak into it. Might want to talk about that.

**Comment by lctrt** [comment]
@AAorris I think I'm fine with this (for now) as this is css variables, and it's only for the theme. It would be easy to alias these to anything if prefered.

**Comment by neauoire** [comment]
I like that, could you make an example that uses the theme's color?

**Pull request merged**
