### PR TITLE
More safe 'and', 'or'

### PR DESCRIPTION
**Pull request by xvw**
It is same as your implementation instead of the last indexation is not necessary.

### CODE REVIEW

**Comment by lctrt** [comment]
@xvw the current implementation is to allow the javascript & clojure like implementation:
* AND: return the first false or last element 
* OR: return the first true or last element

**Comment by lctrt** [comment]
I would be happy to have a (every) and (some) in addition to the current functions

**Comment by neauoire** [comment]
I had no idea js had these 2 methods actually.

**Comment by xvw** [comment]
@lctrt 
In clojure (and JS) it make sense since and, or are binary-f. Here, how to deal with an empty list?
I suggest this implementation.

**Comment by lctrt** [comment]
@xvw that's a good point. Let's use the performant implementation.

**Pull request merged**
